export default function Test() {
  return (
    <div className="h-screen w-full items-center justify-center flex flex-col relative">
      <MotionText_afd0c9 />
    </div>
  );
}

/*
This code is generated by the playground 
engine and matches with the current state 
of the animation. You can copy&paste, 
ready-to-use in seconds!
*/
import MotionText from "@/motion/motion-text";

export function MotionText_afd0c9() {
  return (
    <MotionText
      elementType="p"
      animation={{
        mode: ["filterBlurIn", "fadeDown"],
        transition: "smooth",
        duration: 1,
      }}
      config={{
        duration: 0.12,
        mode: "chars",
        delayLogic: "linear",
      }}
    >
      Hello World!
    </MotionText>
  );
}

/*
This code is generated by the playground 
engine and matches with the current state 
of the animation. You can copy&paste, 
ready-to-use in seconds!
*/
import MotionContainer from "@/motion/motion-container";

export function MotionContainer_667f9a() {
  return (
    <MotionContainer
      elementType="div"
      animation={{
        mode: ["fadeIn"],
        transition: "smooth",
        duration: 1,
      }}
      className="size-24 rounded-lg bg-lime-400"
    />
  );
}
