export default function Test() {
  return (
    <div className="h-screen items-center justify-center flex flex-col w-full">
      <MotionChain_9ec026 />
    </div>
  );
}

/*
This code is generated by the playground 
engine and matches with the current state 
of the animation. You can copy&paste, 
ready-to-use in seconds!
*/

import MotionChain from "@/motion/motion-chain";
import { MotionAnimationProps } from "@/motion/types";

const items = Array.from({ length: 5 }, (_, i) => (
  <div className="size-12 my-1 rounded-2xl bg-stone-700 text-white grid place-items-center">
    {i + 1}
  </div>
));
const animations = items.map(() => ({
  mode: ["scaleZoomIn", "fadeIn"],
  transition: "cubicBounce",
  duration: 2.5,
})) as MotionAnimationProps[];

export function MotionChain_9ec026() {
  return (
    <MotionChain
      animations={animations}
      config={{
        duration: 0.15,
        delayLogic: "linear",
      }}
      elementType="div"
    >
      {items}
    </MotionChain>
  );
}
